# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: /var/log | GSoC 2016
email: mehra.akul@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Static Blog for updates during GSoC 2016. Made using Jekyll !
baseurl: "/gsoc2016" # the subpath of your site, e.g. /blog
url: "http://akulmehra.me" # the base hostname & protocol for your site
twitter_username: AkulMehra
github_username:  akul08

# Build settings
markdown: kramdown
